#! /bin/bash

# $Id: make-links 476 2007-02-24 15:26:29Z genehack $

# note: assumes that current directory is ~
# it's the responsibility of the caller to make it so.

# (otherwise, testing is hard.)



if [ -e .common/flac-jacket ]; then
    for i in convert-mp3-dir eyeD3 flakker make-cover retag retag-whole-tree ; do
        /bin/ln -sfv ~/.common/flac-jacket/bin/$i bin/
    done

    /bin/ln -sfv ~/.common/flac-jacket/lib/FlacJacket.pm lib/
fi

